### ISSUE TITLE
Allow configuration to the connection string

### ISSUE THREAD

**Issue by erikthorselius** [WangXiangUSTC/tidb-lite#18]
Allowing to append/configure the connection string would help us a lot, in our case it is the parseTime=True configuration we need.
 
https://github.com/WangXiangUSTC/tidb-lite/blob/master/tidb.go#L144
```go
// CreateConn creates a database connection.
func (t *TiDBServer) CreateConn() (*sql.DB, error) {
	var dbDSN string
	if t.cfg.Port != 0 {
		dbDSN = fmt.Sprintf("%s:%s@tcp(%s:%d)/?charset=utf8mb4&parseTime=True", "root", "", "127.0.0.1", t.cfg.Port)
	} else {
		dbDSN = fmt.Sprintf("%s:%s@unix(%s)/?charset=utf8mb4&parseTime=True", "root", "", t.cfg.Socket)
	}
...
}
```

**Comment by WangXiangUSTC** [comment]
It looks good to me, do you willing to do this feature?

**Comment by erikthorselius** [comment]
maybe as a parameter to NewOptions()?

**Comment by WangXiangUSTC** [comment]
maybe add a new function like `WithSocket` and `WithPort`

**Comment by erikthorselius** [comment]
https://github.com/WangXiangUSTC/tidb-lite/pull/19

**Comment by erikthorselius** [comment]
Sorry, i made a error in the pr. I pushed a new version
