### ISSUE TITLE
确定这个go 的func会跑起来？ 看起来 go程可能没有创建，函数就已经返回了。

### ISSUE THREAD

**Issue by XuHaoIgeneral** [WangXiangUSTC/tidb-lite#7]
https://github.com/WangXiangUSTC/tidb-lite/blob/cd1aef7c60cfb6bdcb6409cd43f856da45647a30/tidb.go#L89

**Comment by XuHaoIgeneral** [comment]
> https://github.com/WangXiangUSTC/tidb-lite/blob/cd1aef7c60cfb6bdcb6409cd43f856da45647a30/tidb.go#L89

**Comment by WangXiangUSTC** [comment]
没事，欢迎使用
